from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .models import CategoryResult, Database


def _lua(value: Any, indent: int = 0) -> str:
    pad = "    " * indent
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value:.6f}".rstrip("0").rstrip(".")
    if isinstance(value, list):
        if not value:
            return "{}"
        body = ",\n".join(f"{'    ' * (indent + 1)}{_lua(item, indent + 1)}" for item in value)
        return "{\n" + body + ",\n" + pad + "}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = []
        for key in sorted(value, key=lambda x: (str(type(x)), str(x))):
            rendered = key if isinstance(key, str) and re.fullmatch(r"[A-Za-z_]\w*", key) else f"[{_lua(key)}]"
            lines.append(f"{'    ' * (indent + 1)}{rendered} = {_lua(value[key], indent + 1)}")
        return "{\n" + ",\n".join(lines) + ",\n" + pad + "}"
    raise TypeError(f"Unsupported Lua value: {type(value)!r}")


def _category(category: CategoryResult | None) -> dict[str, Any] | None:
    if category is None:
        return None
    return {**category.value, "sampleSize": category.sample_size,
            "generatedAt": category.generated_at, "stale": category.stale}


def render(database: Database) -> str:
    specs: dict[int, Any] = {}
    for spec_id, spec in sorted(database.specs.items()):
        entry = {"metadata": spec.metadata}
        for name in ("stats", "trinkets", "talents"):
            value = _category(getattr(spec, name))
            if value is not None:
                entry[name] = value
        specs[spec_id] = entry
    root = {
        "schemaVersion": database.schema_version, "generatedAt": database.generated_at,
        "gameVersion": database.game_version, "seasonSlug": database.season_slug,
        "sourceMode": database.source_mode, "contexts": {"mythicplus": specs},
    }
    return "-- Generated by EasyStats pipeline. Do not edit.\nEasyStatsGeneratedDB = " + _lua(root) + "\n"


def validate_text(text: str) -> None:
    if not text.startswith("-- Generated by EasyStats") or "contexts" not in text:
        raise ValueError("Invalid generated Lua")
    forbidden = ("characterName", "realmName", "battleTag", "Authorization", "client_secret")
    if any(token in text for token in forbidden):
        raise ValueError("Generated Lua contains forbidden private data")


def write_atomic(path: Path, database: Database) -> bool:
    text = render(database)
    validate_text(text)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(".tmp")
    temp.write_text(text, encoding="utf-8", newline="\n")
    validate_text(temp.read_text(encoding="utf-8"))
    temp.replace(path)
    return True

