from pathlib import Path

import pytest

from specmeta_pipeline.cli import build_fixture_database
from specmeta_pipeline.config import Settings
from specmeta_pipeline.lua import render, validate_text, write_atomic
from specmeta_pipeline.models import Database, SpecResult
from specmeta_pipeline.state import merge_lkg


def test_lua_is_deterministic_and_private(tmp_path: Path) -> None:
    db = build_fixture_database(Settings())
    assert render(db) == render(db)
    assert "fixture-realm" not in render(db)
    path = tmp_path / "GeneratedData.lua"
    assert write_atomic(path, db)
    assert not write_atomic(path, db)


def test_empty_database_is_rejected() -> None:
    empty = Database(1, 1, "x", "s", "fixture", {253: SpecResult()})
    with pytest.raises(ValueError, match="empty"):
        merge_lkg(empty, None, Settings(), now=1)


def test_partial_update_keeps_last_known_good() -> None:
    old = build_fixture_database(Settings())
    new = build_fixture_database(Settings())
    old_talents = old.specs[253].talents
    new.specs[253].talents = None
    merged = merge_lkg(new, old, Settings(), now=new.generated_at)
    assert merged.specs[253].talents is old_talents


def test_soft_and_hard_stale() -> None:
    old = build_fixture_database(Settings())
    assert old.specs[253].stats is not None
    stamp = old.specs[253].stats.generated_at
    new = Database(1, stamp, "x", "s", "fixture", {})
    soft = merge_lkg(new, old, Settings(), now=stamp + 8 * 86400)
    assert soft.specs[253].stats is not None and soft.specs[253].stats.stale
    hard = merge_lkg(new, old, Settings(), now=stamp + 31 * 86400)
    assert hard.specs[253].stats is None


def test_forbidden_identity_is_rejected() -> None:
    with pytest.raises(ValueError):
        validate_text("-- Generated by EasyStats contexts characterName")
