-- Generated by EasyStats pipeline. Do not edit.
EasyStatsGeneratedDB = {
    contexts = {
        mythicplus = {
            [102] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [103] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [104] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [105] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1467] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1468] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1473] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1480] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787582386,
                    items = {
                        {
                            itemID = 250215,
                            usage = 0.540757,
                        },
                        {
                            itemID = 249343,
                            usage = 0.459719,
                        },
                        {
                            itemID = 249346,
                            usage = 0.35409,
                        },
                        {
                            itemID = 270167,
                            usage = 0.152481,
                        },
                    },
                    sampleSize = 47,
                    stale = false,
                },
            },
            [250] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787582386,
                    items = {
                        {
                            itemID = 249344,
                            usage = 0.241504,
                        },
                        {
                            itemID = 250229,
                            usage = 0.233293,
                        },
                        {
                            itemID = 250245,
                            usage = 0.203904,
                        },
                        {
                            itemID = 273796,
                            usage = 0.156804,
                        },
                    },
                    sampleSize = 103,
                    stale = false,
                },
            },
            [251] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [252] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [253] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [254] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [255] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [256] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [257] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [258] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [259] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [260] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                talents = {
                    generatedAt = 1787582386,
                    importString = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAgZZZmZGmZmZWMzMbDAAAAjBAjZxwQGYWYhWYjBYmBDMA",
                    sampleSize = 47,
                    stale = false,
                    support = 0.230606,
                },
                trinkets = {
                    generatedAt = 1787582386,
                    items = {
                        {
                            itemID = 249343,
                            usage = 0.411631,
                        },
                        {
                            itemID = 260235,
                            usage = 0.292407,
                        },
                        {
                            itemID = 250259,
                            usage = 0.286318,
                        },
                        {
                            itemID = 250215,
                            usage = 0.255483,
                        },
                    },
                    sampleSize = 47,
                    stale = false,
                },
            },
            [261] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [262] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787582386,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.649256,
                        },
                        {
                            itemID = 250214,
                            usage = 0.444209,
                        },
                        {
                            itemID = 250144,
                            usage = 0.14036,
                        },
                        {
                            itemID = 250215,
                            usage = 0.139842,
                        },
                    },
                    sampleSize = 56,
                    stale = false,
                },
            },
            [263] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [264] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787582386,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.223698,
                        },
                        {
                            itemID = 270162,
                            usage = 0.170512,
                        },
                        {
                            itemID = 193757,
                            usage = 0.161207,
                        },
                        {
                            itemID = 264507,
                            usage = 0.139114,
                        },
                    },
                    sampleSize = 94,
                    stale = false,
                },
            },
            [266] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [267] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [268] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [269] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [270] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [577] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [581] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [62] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                talents = {
                    generatedAt = 1787582386,
                    importString = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMGAAAGAwMz0sssMDAEbAAsBzMDbWmxMLzYMzMzMswMzMzMAADAAwAMzAMAYYmZA",
                    sampleSize = 106,
                    stale = false,
                    support = 0.282568,
                },
                trinkets = {
                    generatedAt = 1787582386,
                    items = {
                        {
                            itemID = 250215,
                            usage = 0.649166,
                        },
                        {
                            itemID = 270164,
                            usage = 0.179648,
                        },
                        {
                            itemID = 273796,
                            usage = 0.168753,
                        },
                        {
                            itemID = 249343,
                            usage = 0.13128,
                        },
                    },
                    sampleSize = 106,
                    stale = false,
                },
            },
            [64] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [65] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787582386,
                    items = {
                        {
                            itemID = 270162,
                            usage = 0.299168,
                        },
                        {
                            itemID = 273796,
                            usage = 0.283344,
                        },
                        {
                            itemID = 250215,
                            usage = 0.208467,
                        },
                        {
                            itemID = 250214,
                            usage = 0.197166,
                        },
                    },
                    sampleSize = 77,
                    stale = false,
                },
            },
            [66] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [70] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [71] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787582386,
                    items = {
                        {
                            itemID = 249342,
                            usage = 0.430387,
                        },
                        {
                            itemID = 273796,
                            usage = 0.334024,
                        },
                        {
                            itemID = 250229,
                            usage = 0.180583,
                        },
                        {
                            itemID = 260235,
                            usage = 0.164185,
                        },
                    },
                    sampleSize = 129,
                    stale = false,
                },
            },
            [72] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [73] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
        },
    },
    gameVersion = "retail",
    generatedAt = 1787582386,
    schemaVersion = 1,
    seasonSlug = "season-mn-2",
    sourceMode = "hybrid",
}
