-- Generated by EasyStats pipeline. Do not edit.
EasyStatsGeneratedDB = {
    contexts = {
        mythicplus = {
            [102] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787584786,
                    order = {
                        "MASTERY",
                        "HASTE",
                        "CRIT",
                        "VERSATILITY",
                    },
                    sampleSize = 40,
                    scores = {
                        CRIT = 0.273192,
                        HASTE = 0.313703,
                        MASTERY = 0.335472,
                        VERSATILITY = 0.061359,
                    },
                    separators = {
                        "≈",
                        ">",
                        ">",
                    },
                    stale = false,
                },
                talents = {
                    generatedAt = 1787584786,
                    importString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMgxMLzsYmZswyMLjxMjNMAYstNzgxsNCMBAAAYhZmZGsZMjxAAwMDWGA",
                    sampleSize = 40,
                    stale = false,
                    support = 0.16376,
                },
                trinkets = {
                    generatedAt = 1787584786,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.417083,
                        },
                        {
                            itemID = 249343,
                            usage = 0.244266,
                        },
                        {
                            itemID = 249346,
                            usage = 0.164476,
                        },
                        {
                            itemID = 270164,
                            usage = 0.162445,
                        },
                    },
                    sampleSize = 40,
                    stale = false,
                },
            },
            [103] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [104] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [105] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1467] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1468] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1473] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1480] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787622977,
                    order = {
                        "HASTE",
                        "MASTERY",
                        "CRIT",
                        "VERSATILITY",
                    },
                    sampleSize = 48,
                    scores = {
                        CRIT = 0.308222,
                        HASTE = 0.33611,
                        MASTERY = 0.325695,
                        VERSATILITY = 0.026374,
                    },
                    separators = {
                        "≈",
                        "≈",
                        ">",
                    },
                    stale = false,
                },
                talents = {
                    generatedAt = 1787590759,
                    importString = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
                    sampleSize = 48,
                    stale = false,
                    support = 0.16696,
                },
                trinkets = {
                    generatedAt = 1787622977,
                    items = {
                        {
                            itemID = 250215,
                            usage = 0.653578,
                        },
                        {
                            itemID = 249343,
                            usage = 0.409565,
                        },
                        {
                            itemID = 249346,
                            usage = 0.264092,
                        },
                        {
                            itemID = 270167,
                            usage = 0.147064,
                        },
                    },
                    sampleSize = 48,
                    stale = false,
                },
            },
            [250] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787622977,
                    order = {
                        "HASTE",
                        "CRIT",
                        "MASTERY",
                        "VERSATILITY",
                    },
                    sampleSize = 104,
                    scores = {
                        CRIT = 0.268932,
                        HASTE = 0.32749,
                        MASTERY = 0.256726,
                        VERSATILITY = 0.172644,
                    },
                    separators = {
                        ">",
                        "≈",
                        ">",
                    },
                    stale = false,
                },
                trinkets = {
                    generatedAt = 1787622977,
                    items = {
                        {
                            itemID = 250229,
                            usage = 0.238772,
                        },
                        {
                            itemID = 250245,
                            usage = 0.199837,
                        },
                        {
                            itemID = 250228,
                            usage = 0.183251,
                        },
                        {
                            itemID = 249344,
                            usage = 0.172562,
                        },
                    },
                    sampleSize = 108,
                    stale = false,
                },
            },
            [251] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [252] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787584786,
                    order = {
                        "CRIT",
                        "MASTERY",
                        "HASTE",
                        "VERSATILITY",
                    },
                    sampleSize = 54,
                    scores = {
                        CRIT = 0.408084,
                        HASTE = 0.157045,
                        MASTERY = 0.401258,
                        VERSATILITY = 0.030436,
                    },
                    separators = {
                        "≈",
                        ">",
                        ">",
                    },
                    stale = false,
                },
                trinkets = {
                    generatedAt = 1787584786,
                    items = {
                        {
                            itemID = 249344,
                            usage = 0.668033,
                        },
                        {
                            itemID = 249343,
                            usage = 0.628966,
                        },
                        {
                            itemID = 270175,
                            usage = 0.123342,
                        },
                        {
                            itemID = 273797,
                            usage = 0.102035,
                        },
                    },
                    sampleSize = 55,
                    stale = false,
                },
            },
            [253] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [254] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [255] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [256] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [257] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [258] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [259] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [260] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787590759,
                    order = {
                        "CRIT",
                        "HASTE",
                        "VERSATILITY",
                        "MASTERY",
                    },
                    sampleSize = 45,
                    scores = {
                        CRIT = 0.3845,
                        HASTE = 0.338853,
                        MASTERY = 0.123665,
                        VERSATILITY = 0.13266,
                    },
                    separators = {
                        ">",
                        ">",
                        "≈",
                    },
                    stale = false,
                },
                talents = {
                    generatedAt = 1787590759,
                    importString = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAgZZZmZGmZmZWMzMbDAAAAjBAjZxwQGYWYhWYjBYmBDMA",
                    sampleSize = 45,
                    stale = false,
                    support = 0.239286,
                },
                trinkets = {
                    generatedAt = 1787590759,
                    items = {
                        {
                            itemID = 249343,
                            usage = 0.364043,
                        },
                        {
                            itemID = 250215,
                            usage = 0.28876,
                        },
                        {
                            itemID = 250259,
                            usage = 0.274062,
                        },
                        {
                            itemID = 260235,
                            usage = 0.261742,
                        },
                    },
                    sampleSize = 45,
                    stale = false,
                },
            },
            [261] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [262] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787622977,
                    order = {
                        "MASTERY",
                        "CRIT",
                        "HASTE",
                        "VERSATILITY",
                    },
                    sampleSize = 58,
                    scores = {
                        CRIT = 0.327049,
                        HASTE = 0.283241,
                        MASTERY = 0.32955,
                        VERSATILITY = 0.058824,
                    },
                    separators = {
                        "≈",
                        ">",
                        ">",
                    },
                    stale = false,
                },
                trinkets = {
                    generatedAt = 1787622977,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.627825,
                        },
                        {
                            itemID = 250214,
                            usage = 0.394972,
                        },
                        {
                            itemID = 250215,
                            usage = 0.165,
                        },
                        {
                            itemID = 250144,
                            usage = 0.140247,
                        },
                    },
                    sampleSize = 61,
                    stale = false,
                },
            },
            [263] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [264] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787622977,
                    order = {
                        "CRIT",
                        "HASTE",
                        "VERSATILITY",
                        "MASTERY",
                    },
                    sampleSize = 99,
                    scores = {
                        CRIT = 0.394077,
                        HASTE = 0.282169,
                        MASTERY = 0.132327,
                        VERSATILITY = 0.195959,
                    },
                    separators = {
                        ">",
                        ">",
                        ">",
                    },
                    stale = false,
                },
                trinkets = {
                    generatedAt = 1787622977,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.223116,
                        },
                        {
                            itemID = 193757,
                            usage = 0.205203,
                        },
                        {
                            itemID = 270162,
                            usage = 0.174146,
                        },
                        {
                            itemID = 264507,
                            usage = 0.162034,
                        },
                    },
                    sampleSize = 99,
                    stale = false,
                },
            },
            [265] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [266] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [267] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [268] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787584786,
                    order = {
                        "CRIT",
                        "MASTERY",
                        "VERSATILITY",
                        "HASTE",
                    },
                    sampleSize = 41,
                    scores = {
                        CRIT = 0.380723,
                        HASTE = 0.061431,
                        MASTERY = 0.274043,
                        VERSATILITY = 0.253499,
                    },
                    separators = {
                        ">",
                        "≈",
                        ">",
                    },
                    stale = false,
                },
                trinkets = {
                    generatedAt = 1787584786,
                    items = {
                        {
                            itemID = 250215,
                            usage = 0.308522,
                        },
                        {
                            itemID = 249343,
                            usage = 0.288889,
                        },
                        {
                            itemID = 250245,
                            usage = 0.176543,
                        },
                        {
                            itemID = 273797,
                            usage = 0.171807,
                        },
                    },
                    sampleSize = 41,
                    stale = false,
                },
            },
            [269] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [270] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [577] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [581] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [62] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787622977,
                    order = {
                        "HASTE",
                        "CRIT",
                        "MASTERY",
                        "VERSATILITY",
                    },
                    sampleSize = 111,
                    scores = {
                        CRIT = 0.281776,
                        HASTE = 0.369868,
                        MASTERY = 0.194128,
                        VERSATILITY = 0.167055,
                    },
                    separators = {
                        ">",
                        ">",
                        ">",
                    },
                    stale = false,
                },
                talents = {
                    generatedAt = 1787622977,
                    importString = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMGAAAGAwMz0sssMDAEbAAsBzMDbWmxMLzYMzMzMswMzMzMAADAAwAMzAMAYYmZA",
                    sampleSize = 112,
                    stale = false,
                    support = 0.285561,
                },
                trinkets = {
                    generatedAt = 1787622977,
                    items = {
                        {
                            itemID = 250215,
                            usage = 0.679199,
                        },
                        {
                            itemID = 270164,
                            usage = 0.158179,
                        },
                        {
                            itemID = 250224,
                            usage = 0.144923,
                        },
                        {
                            itemID = 249343,
                            usage = 0.142493,
                        },
                    },
                    sampleSize = 112,
                    stale = false,
                },
            },
            [63] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [64] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [65] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787622977,
                    order = {
                        "HASTE",
                        "MASTERY",
                        "CRIT",
                        "VERSATILITY",
                    },
                    sampleSize = 73,
                    scores = {
                        CRIT = 0.241754,
                        HASTE = 0.33833,
                        MASTERY = 0.274899,
                        VERSATILITY = 0.130961,
                    },
                    separators = {
                        ">",
                        ">",
                        ">",
                    },
                    stale = false,
                },
                trinkets = {
                    generatedAt = 1787622977,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.273817,
                        },
                        {
                            itemID = 270162,
                            usage = 0.234655,
                        },
                        {
                            itemID = 250214,
                            usage = 0.231491,
                        },
                        {
                            itemID = 250215,
                            usage = 0.191452,
                        },
                    },
                    sampleSize = 73,
                    stale = false,
                },
            },
            [66] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [70] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [71] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                stats = {
                    generatedAt = 1787622977,
                    order = {
                        "CRIT",
                        "HASTE",
                        "MASTERY",
                        "VERSATILITY",
                    },
                    sampleSize = 133,
                    scores = {
                        CRIT = 0.40248,
                        HASTE = 0.358974,
                        MASTERY = 0.190936,
                        VERSATILITY = 0.045734,
                    },
                    separators = {
                        ">",
                        ">",
                        ">",
                    },
                    stale = false,
                },
                trinkets = {
                    generatedAt = 1787622977,
                    items = {
                        {
                            itemID = 249342,
                            usage = 0.46209,
                        },
                        {
                            itemID = 273796,
                            usage = 0.34078,
                        },
                        {
                            itemID = 250229,
                            usage = 0.187129,
                        },
                        {
                            itemID = 260235,
                            usage = 0.18043,
                        },
                    },
                    sampleSize = 134,
                    stale = false,
                },
            },
            [72] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [73] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
        },
    },
    gameVersion = "retail",
    generatedAt = 1787622977,
    schemaVersion = 1,
    seasonSlug = "season-mn-2",
    sourceMode = "hybrid",
}
