-- Generated by EasyStats pipeline. Do not edit.
EasyStatsGeneratedDB = {
    contexts = {
        mythicplus = {
            [102] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                talents = {
                    generatedAt = 1787584375,
                    importString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMgxMLzsYmZswyMLjxMjNMAYstNzgxsNCMBAAAYhZmZGsZMjxAAwMDWGA",
                    sampleSize = 40,
                    stale = false,
                    support = 0.163762,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.417082,
                        },
                        {
                            itemID = 249343,
                            usage = 0.244266,
                        },
                        {
                            itemID = 249346,
                            usage = 0.164477,
                        },
                        {
                            itemID = 270164,
                            usage = 0.162443,
                        },
                    },
                    sampleSize = 40,
                    stale = false,
                },
            },
            [103] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [104] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [105] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1467] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1468] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1473] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [1480] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                talents = {
                    generatedAt = 1787583217,
                    importString = "CgcBAAAAAAAAAAAAAAAAAAAAAAA2mxMzMzYmxwMAAAAAAAMmthZGAAAAAAAAmxMMzMzMzMzMDzsYGjFZhZmZmt2mZmBwwAQgZMYMD",
                    sampleSize = 41,
                    stale = false,
                    support = 0.170577,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 250215,
                            usage = 0.572559,
                        },
                        {
                            itemID = 249343,
                            usage = 0.450852,
                        },
                        {
                            itemID = 249346,
                            usage = 0.345438,
                        },
                        {
                            itemID = 270167,
                            usage = 0.170893,
                        },
                    },
                    sampleSize = 48,
                    stale = false,
                },
            },
            [250] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 250229,
                            usage = 0.27215,
                        },
                        {
                            itemID = 249344,
                            usage = 0.232206,
                        },
                        {
                            itemID = 250245,
                            usage = 0.227987,
                        },
                        {
                            itemID = 273796,
                            usage = 0.140957,
                        },
                    },
                    sampleSize = 105,
                    stale = false,
                },
            },
            [251] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [252] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 249344,
                            usage = 0.668033,
                        },
                        {
                            itemID = 249343,
                            usage = 0.628968,
                        },
                        {
                            itemID = 270175,
                            usage = 0.123342,
                        },
                        {
                            itemID = 273797,
                            usage = 0.102035,
                        },
                    },
                    sampleSize = 55,
                    stale = false,
                },
            },
            [253] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [254] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [255] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [256] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [257] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [258] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [259] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [260] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                talents = {
                    generatedAt = 1787584375,
                    importString = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAgZZZmZGmZmZWMzMbDAAAAjBAjZxwQGYWYhWYjBYmBDMA",
                    sampleSize = 46,
                    stale = false,
                    support = 0.235451,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 249343,
                            usage = 0.399234,
                        },
                        {
                            itemID = 260235,
                            usage = 0.298551,
                        },
                        {
                            itemID = 250259,
                            usage = 0.292354,
                        },
                        {
                            itemID = 250215,
                            usage = 0.260854,
                        },
                    },
                    sampleSize = 46,
                    stale = false,
                },
            },
            [261] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [262] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.660169,
                        },
                        {
                            itemID = 250214,
                            usage = 0.471664,
                        },
                        {
                            itemID = 250215,
                            usage = 0.133282,
                        },
                        {
                            itemID = 250144,
                            usage = 0.130951,
                        },
                    },
                    sampleSize = 58,
                    stale = false,
                },
            },
            [263] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [264] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 273796,
                            usage = 0.223428,
                        },
                        {
                            itemID = 270162,
                            usage = 0.170308,
                        },
                        {
                            itemID = 193757,
                            usage = 0.161014,
                        },
                        {
                            itemID = 264507,
                            usage = 0.138946,
                        },
                    },
                    sampleSize = 94,
                    stale = false,
                },
            },
            [266] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [267] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [268] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 250215,
                            usage = 0.308525,
                        },
                        {
                            itemID = 249343,
                            usage = 0.28889,
                        },
                        {
                            itemID = 250245,
                            usage = 0.176542,
                        },
                        {
                            itemID = 273797,
                            usage = 0.171806,
                        },
                    },
                    sampleSize = 41,
                    stale = false,
                },
            },
            [269] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [270] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [577] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [581] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [62] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                talents = {
                    generatedAt = 1787584375,
                    importString = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMGAAAGAwMz0sssMDAEbAAsBzMDbWmxMLzYMzMzMswMzMzMAADAAwAMzAMAYYmZA",
                    sampleSize = 107,
                    stale = false,
                    support = 0.276134,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 250215,
                            usage = 0.658015,
                        },
                        {
                            itemID = 270164,
                            usage = 0.176966,
                        },
                        {
                            itemID = 273796,
                            usage = 0.1645,
                        },
                        {
                            itemID = 249343,
                            usage = 0.127971,
                        },
                    },
                    sampleSize = 107,
                    stale = false,
                },
            },
            [64] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [65] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 270162,
                            usage = 0.305549,
                        },
                        {
                            itemID = 273796,
                            usage = 0.261876,
                        },
                        {
                            itemID = 250215,
                            usage = 0.229027,
                        },
                        {
                            itemID = 250214,
                            usage = 0.20522,
                        },
                    },
                    sampleSize = 79,
                    stale = false,
                },
            },
            [66] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [70] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [71] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
                trinkets = {
                    generatedAt = 1787584375,
                    items = {
                        {
                            itemID = 249342,
                            usage = 0.415318,
                        },
                        {
                            itemID = 273796,
                            usage = 0.348114,
                        },
                        {
                            itemID = 250229,
                            usage = 0.181211,
                        },
                        {
                            itemID = 260235,
                            usage = 0.164786,
                        },
                    },
                    sampleSize = 128,
                    stale = false,
                },
            },
            [72] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
            [73] = {
                metadata = {
                    methodologyVersion = 1,
                    regionCount = 4,
                },
            },
        },
    },
    gameVersion = "retail",
    generatedAt = 1787584375,
    schemaVersion = 1,
    seasonSlug = "season-mn-2",
    sourceMode = "hybrid",
}
